name: 'Set Careflow as Live'
description:
  'Used inside of a synced Awell Careflow respository to set the careflow as
  live.'
author: 'Awell Health'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  github-token:
    description: 'The GitHub token to use for authentication.'
    required: true
  api-key:
    description: 'The Awell API key to use for authentication.'
    required: true
  awell-environment:
    description: 'The Awell environment to use.'
    required: true
    default: development

# Define your outputs here.
outputs:
  request-id:
    description: 'The ID of the request that was sent to the Awell API.'
  result:
    description: 'The result of the request that was sent to the Awell API.'
  release_id:
    description: 'The ID of the release that was marked as live.'
  definition_id:
    description: 'The definition ID of the repository care flow.'

runs:
  using: node20
  main: dist/index.js
