name: 'Set Careflow as Live'
description:
  'Used inside of a synced Awell Careflow respository to set the careflow as
  live.'
author: 'Awell Health'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  github_token:
    description: 'The GitHub token to use for authentication.'
    required: true
  api_key:
    description: 'The Awell API key to use for authentication.'
    required: true
  awell_environment:
    description: 'The Awell environment to use.'
    required: true
    default: development
  test_mode:
    description: 'Whether to run in test mode.'
    required: false
  release_id:
    description: 'The release ID to mark as live, if running in test mode.'
    required: false
  definition_id:
    description:
      'The definition ID of the repository care flow, if running in test mode.'
    required: false

# Define your outputs here.
outputs:
  result:
    description: 'The result of the request that was sent to the Awell API.'
  release_id:
    description: 'The ID of the release that was marked as live.'
  definition_id:
    description: 'The definition ID of the repository care flow.'

runs:
  using: node20
  main: dist/index.js
